name: Arguments

description: |-
  Various arguments

inputs:
  name:
    description: "The name to congrats"
    required: true
  path:
    description: "The path used to store data"
    required: true

outputs:
  path:
    description: "The path used to store data"
    value: ${{ steps.path_resolver.outputs.path }}

runs:
  using: "composite"
  steps:
    - shell: bash
      run: echo "hello ${{ inputs.name || 'you' }}"

    - id: path_resolver
      shell: bash
      env:
        PATH: ${{ inputs.path }}
      run: echo "path=${PATH:-./default-path}" >> $GITHUB_OUTPUT # or "| tee -a $GITHUB_OUTPUT" if available.
