name: Workflow on demand from workflows/reusable/

# Workflow on demand: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#providing-inputs
# How to run: https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
on:
  workflow_call:
    inputs:
      from_workflow_call:
        description: 'To know the trigger was workflow_call'
        required: false
        default: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      text:
        description: 'Input text'
        required: false
        default: bonjour
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        default: Staging

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Step on demand
        run: |
          echo "Text: ${{ inputs.text }}"
          echo "From workflow: ${{ inputs.from_workflow_call }}"
          env
        env:
          DISPATCH_LEVEL: ${{ inputs.logLevel }}
          DISPATCH_TAGS: ${{ inputs.tags }}
          DISPATCH_ENVIRONMENT: ${{ inputs.environment }}
