name: Workflow on demand (workflow_dispatch)

# Workflow on demand: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#providing-inputs
# How to run: https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
on:
  workflow_call:
    inputs:
      from_workflow_call:
        description: 'To know the trigger was workflow_call'
        required: false
        default: true
        type: boolean
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      text:
        description: 'Input text'
        required: false
        default: bonjour
        type: string
      test_mode:
        description: 'Test mode'
        required: false
        default: false
        type: boolean
      environment:
        description: |
          This is a really really really really really really really long description.
          
          This is also using multiple lines with *markdown*.
          This is also using multiple lines with *markdown*.
          
          Otsukare sama desu.
        type: environment
        required: true
        default: Staging

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Step on demand
        env:
          DISPATCH_LEVEL: ${{ inputs.logLevel }}
          DISPATCH_TAGS: ${{ inputs.tags }}
          DISPATCH_ENVIRONMENT: ${{ inputs.environment }}
        run: |
          echo "Text: ${{ inputs.text }}"
          echo "Test mode: ${{ inputs.test_mode || 'false' }}"
          echo "From workflow: ${{ inputs.from_workflow_call }}"
          env
