name: Main workflow

on: [ pull_request ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Android SDK versions
        shell: bash
        run: ./android-sdk-list.sh

      - name: Build args
        id: build-args
        shell: bash
        run: |
          set -o xtrace
          ARGS=""
          if true; then
            ARGS+=" arg1"
            ARGS+=" arg2"
          fi
          if false; then
            ARGS+=" arg3"
          fi
          echo "ARGS=$ARGS" >> $GITHUB_OUTPUT

      - name: Consume args
        shell: bash
        run: |
          command() { echo "arg1=$1 arg2=$2 arg3=$3"; }

          # Notice without "..." it will try to run arg1 as the program
          string="${{ steps.build-args.outputs.ARGS }}"
          echo "As string: $string"
          command $string # Output: arg1=arg1 arg2=arg2 arg3=
          # This is surprising...

          echo "Convert to array"
          read -a array <<< "${{ steps.build-args.outputs.ARGS }}"
          command ${array[@]} # Output: arg1=arg1 arg2=arg2 arg3=
          
      - name: Consume secrets
        shell: bash
        run: |
          echo "${{ secrets.SECRET_VALUE }}" | tr '_' ' '
          echo '${{ secrets.SECRET_VALUE }}' | tr '_' ' '

  reuse_workflow:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      key: value
      enabled_option: true
      disabled_option: false
      opt_key_provided: hello
      not_master: ${{ github.ref_type == 'branch' && github.ref_name != 'main' }}
    secrets: inherit

  utests_debug:
    if: ${{ github.head_ref == 'matrix' }}
    uses: ./.github/workflows/utests.yml
    with:
      flavor: debug
    secrets: inherit

  utests_release:
    if: ${{ github.head_ref == 'matrix' }}
    uses: ./.github/workflows/utests.yml
    with:
      flavor: release
    secrets: inherit

  dispatch:
    uses: ./.github/workflows/dispatch.yml
    secrets: inherit
