on:
  pull_request:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Hello
        shell: bash
        run: echo hello world

  reuse-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      key: value
      enabled_option: true
      disabled_option: false
    secrets: inherit
