on:
  pull_request:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Android SDK versions
        shell: bash
        run: ./android-sdk-list.sh

      - name: Build args
        id: build-args
        shell: bash
        run: |
          set -o xtrace
          ARGS=""
          if true; then
            ARGS+=" arg1"
            ARGS+=" arg2"
          fi
          if false; then
            ARGS+=" arg3"
          fi
          echo "ARGS=$ARGS" >> $GITHUB_OUTPUT

      - name: Consume args
        shell: bash
        run: |
          command() { echo "arg1=$1 arg2=$2 arg3=$3"; }

          # Notice without "..." it will try to run arg1 as the program
          string="${{ steps.build-args.outputs.ARGS }}"
          echo "As string: $string"
          command $string # Output: arg1=arg1 arg2=arg2 arg3=
          # This is surprising...

          echo "Convert to array"
          read -a array <<< "${{ steps.build-args.outputs.ARGS }}"
          command ${array[@]} # Output: arg1=arg1 arg2=arg2 arg3=

  reuse_workflow:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      key: value
      enabled_option: true
      disabled_option: false
      opt_key_provided: hello
    secrets: inherit

  pre_multi_matrix:
    uses: ./.github/workflows/node_matrix_gen.yml
    with:
      node_total: 2

  multi_matrix:
    needs: pre_multi_matrix
    uses: ./.github/workflows/multi_matrix.yml
    strategy:
      matrix:
        suffix: [ "", "Suffix" ]
    with:
      key: Value
      suffix: ${{ matrix.suffix }}
      node_matrix: ${{ needs.pre_multi_matrix.outputs.matrix }}
    secrets: inherit

  # https://github.com/orgs/community/discussions/25338
  post_multi_matrix:
    needs: multi_matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Consume all artifacts
        run: |
          # This will find zip files like: artifacts/Value-1-2/Value-1-2.zip
          find artifacts/ -type f -name "*.zip" | while read artifact_zip; do
            artifact_dir="$(dirname $artifact_zip)"
            echo ">> Extract $artifact_zip in $artifact_dir"
            unzip "$artifact_zip" -d "$artifact_dir"
            rm "$artifact_zip"
          done

          find artifacts/ -type f | while read artifact; do
            echo "Content of $artifact: $(cat $artifact)"
          done
