on:
  pull_request:
  push:
    branches:
      - main
      - android-versions

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build args
        id: build-args
        shell: bash
        run: |
          set -o xtrace
          ARGS=""
          if true; then
            ARGS+=" arg1"
            ARGS+=" arg2"
          fi
          if false; then
            ARGS+=" arg3"
          fi
          echo "ARGS=$ARGS" >> $GITHUB_OUTPUT

      - name: Consume args
        shell: bash
        run: |
          echo "ARGS: ${{ steps.build-args.outputs.ARGS }}"

      - name: Android SDK versions
        shell: bash
        run: ./android-sdk-list.sh

  reuse-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      key: value
      enabled_option: true
      disabled_option: false
      opt_key_provided: hello
    secrets: inherit
