name: Multi matrix workflow

on:
  workflow_call:
    inputs:
      key:
        type: string
        required: true
      suffix:
        type: string
        required: true
      node_matrix:
        type: string
        required: true

jobs:
  workflow:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(inputs.node_matrix)}}        
    steps:
      - name: Resolve inputs
        shell: bash
        env:
          NODE_INDEX: ${{ matrix.node_index }}
          NODE_TOTAL: ${{ matrix.node_total }}
        run: >
          echo
          ./gradlew test${{ inputs.key }}${{ inputs.suffix }}
          -Pindex=$NODE_INDEX
          -Pcount=$NODE_TOTAL
