name: Multi matrix workflow

on:
  workflow_call:
    inputs:
      key:
        type: string
        required: true

jobs:
  workflow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suffix: ["", "Suffix"]
        index: [0, 1, 2, 3]
    steps:
      - name: Resolve inputs
        shell: bash
        run: echo ./gradlew test${{ inputs.key }}${{ matrix.suffix }} -Pindex=${{ matrix.index }}
