name: On pull request review

on: pull_request_review

permissions:
  pull-requests: write

jobs:
  when_approved:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Label when approved
      uses: abinoda/label-when-approved-action@v1.0.7
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "approved"
