name: On push release

on:
  push:
    branches:
      - 'release/[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello release
        shell: bash
        run: echo hello release
  reuse_workflow:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      key: value
      enabled_option: true
      disabled_option: false
      opt_key_provided: hello
      not_master: ${{ github.ref_type == 'branch' && github.ref_name != 'main' }}
    secrets: inherit
  release_job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello release
        shell: bash
        run: echo hello release
