name: On push release

on:
  push:
    branches:
      - 'release/[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello release
        shell: bash
        run: echo hello release
  release_job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello release
        shell: bash
        run: echo hello release
