name: on push tag

on:
  push:
    tags:
      - 'v**'

jobs:
  print_tag:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      key: ${{ github.ref_name }}
      not_master: false
    secrets: inherit
