name: Shell samples

on:
  push:
    branches:
      - 'shell**'

jobs:
  shell-samples:
    runs-on: ubuntu-latest
    steps:
      - name: Shell bash
        shell: bash
        run: echo "hello from bash" && env

      - name: Shell Python3
        shell: python3 {0}
        run: |
          import sys
          print("hello from python %s" % sys.version)

      - name: shell kotlinc
        shell: kotlinc -script {0}
        run: println("hello from kotlin ${KotlinVersion.CURRENT}")
