name: Main workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  dispatch:
    uses: ./.github/workflows/dispatch.yml
    secrets: inherit
  reusable-folder:
    uses: ./.github/workflows/reusable/another-dispatch.yml
    secrets: inherit
  outside-folder:
    uses: ./.github/reusable/another-dispatch.yml
    secrets: inherit
